from django.urls import path
from app1 import views

urlpatterns = [
    path('', views.inicio,name='Inicio'),
    path('Producto/', views.producto,name='Producto'),
    path('ProductoApi/', views.productoApi),
    path('busquedaproducto/', views.buscarproducto),
    path('buscar/', views.buscar),
    path('Vendedor/', views.vendedor,name='Vendedor'),
    path('busquedavendedor/', views.buscarvendedor),
    path('Cliente/', views.cliente,name='Cliente'),
    path('busquedacliente/', views.buscarcliente),
    path('buscar1/', views.buscar1),
    path('buscar2/', views.buscar2),
    path('VendedorApi/', views.vendedorApi),
    path('Cliente/', views.cliente,name='Cliente'),
    path('ClienteApi/', views.clienteApi),
    path('leerProductos/', views.leer_productos),
    path('crearProducto/', views.crear_producto),
    path('editarProducto/', views.editar_producto),
    path('eliminarProducto/', views.eliminar_producto),
    path('producto/list/', views.ProductosList.as_view(),name='List'),
    path("producto/create/", views.ProductosCreate.as_view(),name='New'),
    path("producto/edit/<pk>", views.ProductosEdit.as_view(),name='Edit'),    
    path("producto/detail/<pk>", views.ProductosDetail.as_view(),name='Detail'),
    path("producto/delete/<pk>", views.ProductosDelete.as_view(),name='Delete'),
    #--------------------------------------------------------------------------
    path('leerVendedores/', views.leer_vendedores),
    path('crearVendedor/', views.crear_vendedor),
    path('editarVendedor/', views.editar_vendedor),
    path('eliminarVendedor/', views.eliminar_vendedor),
    path('vendedor/list/', views.VendedoresList.as_view(),name='List'),
    path("vendedor/create/", views.VendedoresCreate.as_view(),name='New'),
    path("vendedor/edit/<pk>", views.VendedoresEdit.as_view(),name='Edit'),    
    path("vendedor/detail/<pk>", views.VendedoresDetail.as_view(),name='Detail'),
    path("vendedor/delete/<pk>", views.VendedoresDelete.as_view(),name='Delete'),
    #--------------------------------------------------------------------------
    path('leerClientes/', views.leer_clientes),
    path('crearCliente/', views.crear_cliente),
    path('editarCliente/', views.editar_cliente),
    path('eliminarCliente/', views.eliminar_cliente),
    path('cliente/list/', views.ClientesList.as_view(),name='List'),
    path("cliente/create/", views.ClientesCreate.as_view(),name='New'),
    path("cliente/edit/<pk>", views.ClientesEdit.as_view(),name='Edit'),    
    path("cliente/detail/<pk>", views.ClientesDetail.as_view(),name='Detail'),
    path("cliente/delete/<pk>", views.ClientesDelete.as_view(),name='Delete'),
]
