# Generated by Django 4.1.3 on 2022-12-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendedor',
            new_name='Clientes',
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Vendedores',
        ),
    ]
